CREATE DATABASE FATURAMENTO;
	USE FATURAMENTO;

-- ENTIDADE ENDERECO QUE ARMAZENARA OS ENDERECO DAS
-- RESPECTIVAS ENTIDADES CLIENTE, FUNCIONARIO E FORNECEDOR.

CREATE TABLE ENDERECO(
	END_CODIGO     INTEGER NOT NULL,
    END_LOGRADOURO VARCHAR(50),
    END_ENDERECO   VARCHAR(50) NOT NULL,
    END_NUMERO     VARCHAR(50) NOT NULL,
    END_BAIRRO     VARCHAR(50),
    END_CIDADE     VARCHAR(50),
    END_CEP        VARCHAR(50) NOT NULL,
    END_UF         CHAR(2)
);

ALTER TABLE ENDERECO
	ADD CONSTRAINT PK_ENDERECO
    PRIMARY KEY (END_CODIGO);
    
-- 
CREATE TABLE CONTATO(
	CON_CODIGO   INTEGER NOT NULL,
    CON_TELEFONE VARCHAR(50),
    CON_CELULAR  VARCHAR(50),
    CON_EMAIL    VARCHAR(70)
);

ALTER TABLE CONTATO
	ADD CONSTRAINT PK_CONTATO
    PRIMARY KEY (CON_CODIGO);
     
CREATE TABLE USUARIO(
	USU_CODIGO    INTEGER NOT NULL,
    USU_NOME      VARCHAR(50),
    USU_SOBRENOME VARCHAR(50),
    USU_LOGIN     VARCHAR(50) NOT NULL UNIQUE,
    USU_SENHA     VARCHAR(50) NOT NULL,
    USU_CADASTRO  VARCHAR(50),
    USU_ATIVO     VARCHAR(50)
);

ALTER TABLE USUARIO
	ADD CONSTRAINT PK_USUARIO
    PRIMARY KEY (USU_CODIGO);

ALTER TABLE USUARIO
	MODIFY USU_CODIGO INTEGER NOT NULL AUTO_INCREMENT;
    
CREATE TABLE FUNCIONARIO(
	FUN_CODIGO     INTEGER NOT NULL,
    END_CODIGO     INTEGER NOT NULL,
    CON_CODIGO     INTEGER NOT NULL UNIQUE,
    FUN_NOME       VARCHAR(50) NOT NULL,
    FUN_CPF        VARCHAR(50) NOT NULL UNIQUE,
    FUN_RG         VARCHAR(50) NOT NULL,
    FUN_CTPS       VARCHAR(50) NOT NULL,
    FUN_SALARIO    DECIMAL(10,2), 
    FUN_DTADMISSAO DATE,	
    FUN_DTDEMISSAO DATE
);

-- RELACIONAMENTO 1:1 
ALTER TABLE CLIENTE 
	MODIFY CON_CODIGO INTEGER NOT NULL UNIQUE;
    
ALTER TABLE FUNCIONARIO
	ADD CONSTRAINT PK_FUNCIONARIO
    PRIMARY KEY (FUN_CODIGO);

ALTER TABLE FUNCIONARIO
	ADD CONSTRAINT FK_ENDERECO_FUNCIONARIO
    FOREIGN KEY (END_CODIGO) REFERENCES ENDERECO (END_CODIGO);

ALTER TABLE FUNCIONARIO
	ADD CONSTRAINT FK_CONTATO_FUNCIONARIO
    FOREIGN KEY (CON_CODIGO) REFERENCES CONTATO (CON_CODIGO);

CREATE TABLE CLIENTE(
	CLI_CODIGO          INTEGER NOT NULL,
    END_CODIGO          INTEGER NOT NULL,
    CON_CODIGO          INTEGER NOT NULL UNIQUE,
    CLI_NOME            VARCHAR(50),
    CLI_CNPJ            VARCHAR(50) NOT NULL,
    CLI_INSCEST         VARCHAR(50) NOT NULL,
    CLI_LIMITECRED      DECIMAL(10,2),
    CLI_COBR_LOGRADOURO VARCHAR(50),
    CLI_COBR_ENDERECO   VARCHAR(50) NOT NULL,
    CLI_COBR_NUMERO     VARCHAR(50) NOT NULL,
    CLI_COBR_BAIRRO     VARCHAR(50),
    CLI_COBR_CIDADE     VARCHAR(50),
    CLI_COBR_CEP        VARCHAR(50) NOT NULL,
    CLI_COBR_UF         CHAR(2)
);

ALTER TABLE CLIENTE
	ADD CONSTRAINT PK_CLIENTE
    PRIMARY KEY (CLI_CODIGO);

ALTER TABLE CLIENTE
	MODIFY CLI_CODIGO INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_ENDERECO_CLIENTE
    FOREIGN KEY (END_CODIGO) REFERENCES ENDERECO (END_CODIGO);

ALTER TABLE CLIENTE
	ADD CONSTRAINT FK_CONTATO_CLIENTE
    FOREIGN KEY (CON_CODIGO) REFERENCES CONTATO (CON_CODIGO);